You've hit the outstandingly rare 
and almost definitely contrived case 
where pushing an error frame via check-error 
caused a stack overflow 
but where that very overflow 
was caught by another check-error. 
Well done.
One of two tests passed.
